name: Terraform Plan

on:
  pull_request:
    paths:
      - "*.tf"

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1
    - name: Init Terraform
      run: terraform init
    - name: Run terraform plan
      run: terraform plan -out=tfplan
    - name: Print tfplan file
      run: cat tfplan

    - name: Create comment
      uses: actions-ecosystem/action-create-comment@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}      
        body: |
              The output of `terraform plan` is:
                           
                  
              ```
              $(sh -c "cat tfplan")
              ```      
              
            
    # - name: Create comment
    #   uses: mshick/add-pr-comment@v2
      
    #   with:
    #     message: |
    #       The output of `terraform plan` is:
          
    #        \$(cat tfplan)          
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

