name: Terraform Plan

on:
  pull_request:
    paths:
      - "*.tf"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Init Terraform
        run: terraform init
      - name: Run terraform plan
        id: terraform
        run: terraform plan
      - name: Comment on pull request
        if: ${{ success() }}
        uses: peter-evans/create-or-update-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |-
            Changes proposed by this pull request:
            ${{ steps.terraform.outputs.plan }}
